services:
  mockserver:
    image: mockserver/mockserver:5.15.0
    container_name: payments-mockserver
    ports:
      - "1080:1080"
    environment:
      MOCKSERVER_SERVER_PORT: "1080"
      MOCKSERVER_INITIALIZATION_JSON_PATH: /config/expectations/transfers_success.json
    volumes:
      - ./mockserver/expectations:/config/expectations:ro

  tests:
    image: python:3.11-slim
    container_name: payments-tests
    working_dir: /workspace/tests
    profiles: ["manual"]
    depends_on:
      mockserver:
        condition: service_started
    env_file:
      - .env.dev
    environment:
      ENV: ${ENV:-dev}
      BASE_URL: ${BASE_URL:-http://mockserver:1080}
      DATASET: ${DATASET:-transfers_dataset.json}
      PYTHONUNBUFFERED: "1"
    volumes:
      - ./tests:/workspace/tests:ro
      - ./scripts:/workspace/scripts:ro
      - ./artifacts:/artifacts
    command: ["/bin/bash", "-lc", "bash /workspace/scripts/run-tests.sh"]

  locust:
    build:
      context: ./performance
    image: cashi-locust:latest
    container_name: payments-locust
    profiles: ["performance"]
    working_dir: /workspace/performance
    depends_on:
      mockserver:
        condition: service_started
    environment:
      BASE_URL: ${BASE_URL:-http://mockserver:1080}
      AUTH_TOKEN: ${AUTH_TOKEN:-}
      HEADLESS: ${HEADLESS:-false}
      USERS: ${USERS:-1000}
      SPAWN_RATE: ${SPAWN_RATE:-100}
      RUN_TIME: ${RUN_TIME:-5m}
      RESPONSE_TIME_THRESHOLD_MS: ${RESPONSE_TIME_THRESHOLD_MS:-2000}
      P95_THRESHOLD_MS: ${P95_THRESHOLD_MS:-2000}
      FAILURE_RATE_THRESHOLD: ${FAILURE_RATE_THRESHOLD:-0.01}
      TRANSFER_PATH: ${TRANSFER_PATH:-/api/v1/transfers}
      TEST_DATA_FILE: ${TEST_DATA_FILE:-test_data.json}
      PYTHONUNBUFFERED: "1"
    volumes:
      - ./performance:/workspace/performance:ro
      - ./artifacts:/artifacts
    ports:
      - "8089:8089"
    command:
      [
        "/bin/bash",
        "-lc",
        "mkdir -p /artifacts/performance && if [ \"$${HEADLESS}\" = \"true\" ]; then locust -f locustfile.py --host=$${BASE_URL} --headless -u $${USERS} -r $${SPAWN_RATE} --run-time $${RUN_TIME} --csv=/artifacts/performance/locust --csv-full-history; else locust -f locustfile.py --host=$${BASE_URL}; fi",
      ]

  allure:
    image: frankescobar/allure-docker-service:latest
    container_name: payments-allure
    user: "0:0"
    ports:
      - "5050:5050"
    environment:
      CHECK_RESULTS_EVERY_SECONDS: "2"
      KEEP_HISTORY: "1"
    volumes:
      - ./artifacts/allure-results:/app/allure-results
      - ./artifacts/allure-reports:/app/default-reports

  jenkins:
    build:
      context: ./jenkins
    image: cashi-jenkins:lts-docker
    container_name: payments-jenkins
    profiles: ["ci"]
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ./:/workspace

volumes:
  jenkins_home:
